name: 'action-xcodeproj-spm-update'
description: 'Update your Xcode project with the latest Swift Package dependencies'
branding:
  icon: "package"
  color: "purple"
inputs:
  directory:
    description: 'The path in which the Xcodeproj can be found.'
    required: false
    default: '.'
  project:
    description: 'The Xcodeproj that holds the SPM data'
    required: true
  forceResolution:
    description: 'Always regenerate the Package.resolved, irrespective of conflicts.'
    required: false
    default: false
  failWhenOutdated:
    description: 'Action will fail if changes to dependencies are made.'
    required: false
    default: true
outputs:
  dependenciesChanged:
    description: 'A bool (true or false) indicating whether changes were made to the dependencies.'
    value: ${{ steps.script.outputs.dependenciesChanged }}
runs:
  using: 'composite'
  steps:
    - run: brew install md5sha1sum
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: script
      run: entrypoint.sh -a "${{ inputs.directory }}" -b "${{ inputs.project }}" -c "${{ inputs.failWhenOutdated }}" -d "${{ inputs.forceResolution }}"
      shell: bash